sudo: required

language: node_js
node_js:
  - "6.2"

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.7.0

script:
  - docker-compose up -d chrome-swarm && docker ps && date
  - docker-compose up nodejs