version: "2"
services:
  selenium-hub:
    image: selenium/hub:2.53.0
    ports:
      - "4444:4444"
    environment:
      GRID_TIMEOUT: 10000

  chrome-debug:
    container_name: "chrome-debug"
    image: selenium/node-chrome-debug:2.53.0
    #one of the OpenDNS IPs
    dns: 208.67.222.222
    ports:
      - "5900:5900"
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    depends_on:
      - selenium-hub

  chrome-swarm:
    image: selenium/node-chrome:2.53.0
    dns: 208.67.222.222
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    depends_on:
      - selenium-hub

  firefox-debug:
    container_name: "firefox-debug"
    image: selenium/node-firefox-debug:2.53.0
    ports:
      - "5901:5900"
    dns: 208.67.222.222
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    depends_on:
      - selenium-hub

  firefox-swarm:
    image: selenium/node-firefox:2.53.0
    dns: 208.67.222.222
    extra_hosts:
      - "mage19.docker:192.168.99.100"
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    depends_on:
      - selenium-hub

  nodejs:
    container_name: nodejs
    image: node:4
    ports:
      - "9001:9000"
    volumes:
      - ./:/tests
    working_dir: /tests
    depends_on:
      - selenium-hub
      - chrome-debug
    command: "node /tests/node_modules/protractor/bin/protractor /tests/conf.js"